name: Integration CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Japanese fonts
      run: | 
        sudo apt-get update
        sudo apt-get install -y fonts-takao
    - name: Start services
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "SQLALCHEMY_DATABASE_URI=sqlite:///:memory:" > .env
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
        docker build -t code-snippet-app .
        docker run -d -p 8000:8000 --env-file .env --name code-snippet-app code-snippet-app
    - name: Install test dependencies
      run: cd tests/integration && yarn
    - name: Wait for services to start
      run: |
        until $(curl --output /dev/null --silent --fail http://localhost:8000); do
          printf '.'
          sleep 5
        done
    - name: Run integration tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: tests/integration
    - name: Tear down services
      run: |
        docker stop code-snippet-app
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: tests/integration/cypress/videos
