name: Repo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install commitlint
      run: yarn global add @commitlint/cli @commitlint/config-conventional
    - name: Run commitlint
      run: |
        echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
        commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
